### PR TITLE
Add a README section about vmnet support

### PR DESCRIPTION
**Pull request by dguerri**

### CODE REVIEW

**Comment by dguerri** [comment]
aaaargh my github sucks :) Let me fix this

**Comment by dguerri** [comment]
this sucks even more as it created 3 commits :P

**Comment by dguerri** [comment]
Fixed... never use the UI again for these :D

**Review by knazarov — CHANGES_REQUESTED** [review]

**Comment by dguerri** [comment]
For some reason, my forced push doesn't update automatically this PR. 

The branch contains the requested changes changes https://github.com/dguerri/homebrew-qemu-virgl/tree/vmnet

**Comment by dguerri** [comment]
I give up... I will open a new one :(

**Pull request closed without merging**
